version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "sigstore/cosign-installer"
        update-types: ["version-update:semver-major"]
