{{- /*
Validate web config options.
*/ -}}
{{- if and .Values.web.config .Values.web.configSecretRef.name -}}
{{- fail "Invalid values: 'web.config' and 'web.configSecretRef.name' cannot both be set. Set at most one." -}}
{{- end -}}
