{{ if .Values.instance.sync.pullSecretStringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flux-instance.fullname" . }}-pull
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-instance.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- toYaml .Values.instance.sync.pullSecretStringData | nindent 2 }}
{{ end }}
