# Default values for flux-operator.

nameOverride: ""
fullnameOverride: ""

# -- Install and upgrade the custom resource definitions.
installCRDs: true

# -- Common annotations to add to all deployed objects.
commonAnnotations: {}

# -- Common labels to add to all deployed objects.
commonLabels: {}

# -- Container image settings.
# The image tag defaults to the chart appVersion.
image:
  repository: ghcr.io/controlplaneio-fluxcd/flux-operator # @schema required: true
  tag: ""
  pullSecrets: [ ]

# -- Pod priority class name.
# Recommended value is system-cluster-critical.
priorityClassName: ""

# -- Pod security context settings.
podSecurityContext: {}
  # fsGroup: 1337

# -- Container security context settings.
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

# -- Container resources requests and limits settings.
resources:
   limits:
     cpu: 1000m
     memory: 1Gi
   requests:
     cpu: 100m
     memory: 64Mi

# -- Container liveness probe settings.
livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

# -- Container readiness probe settings.
readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

# -- Pod service account settings.
# The name of the service account defaults to the release name.
serviceAccount:
  automount: true
  name: ""

# -- Pod affinity and anti-affinity settings.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux

# -- Pod tolerations settings.
tolerations: []
