{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flux-operator-mcp.fullname" . }}
  labels:
    {{- include "flux-operator-mcp.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    apiVersion: mcp.fluxcd.controlplane.io/v1
    kind: Config
    spec:
      {{- toYaml .Values.config.spec | nindent 6 }}
{{- end }}
