apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flux-operator-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-operator-mcp.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "flux-operator-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.config.enabled .Values.commonAnnotations }}
      annotations:
      {{- end }}
      {{- if .Values.config.enabled }}
        checksum/config: {{ (include (print $.Template.BasePath "/configmap.yaml") . | fromYaml).data | toYaml | sha256sum }}
      {{- end }}
      {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flux-operator-mcp.labels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flux-operator-mcp.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          args:
            - serve
            - --transport={{ .Values.transport }}
            - --port=9090
            - --read-only={{ .Values.readonly }}
            {{- if .Values.config.enabled }}
            - --config=/etc/flux-mcp/config/config.yaml
            {{- end }}
            {{- range .Values.extraArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: temp
              mountPath: /tmp
          {{- if .Values.config.enabled }}
            - name: config
              mountPath: /etc/flux-mcp/config
              readOnly: true
          {{- end }}
      volumes:
        - name: temp
          emptyDir: {}
      {{- if .Values.config.enabled }}
        - name: config
          configMap:
            name: {{ include "flux-operator-mcp.fullname" . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

