{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "flux-operator-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-operator-mcp.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      {{- include "flux-operator-mcp.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        {{- range $ns := .Values.networkPolicy.ingress.namespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ns }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 9090
{{- end }}
