apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux-operator-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-operator-mcp.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flux-operator-mcp.selectorLabels" . | nindent 4 }}
