apiVersion: v2
version: 0.26.0
appVersion: "v0.26.0"
kubeVersion: ">=1.27.0-0"
type: application
name: flux-operator-mcp
description: |
  A Helm chart for deploying the Flux MCP Server.
home: https://github.com/controlplaneio-fluxcd
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/flux/icon/color/flux-icon-color.png
sources:
  - https://github.com/controlplaneio-fluxcd/flux-operator
  - https://github.com/controlplaneio-fluxcd/charts
annotations:
  "artifacthub.io/license": AGPL-3.0
  "artifacthub.io/links": |
    - name: Documentation
      url: https://fluxcd.control-plane.io/mcp
    - name: Chart Source
      url: https://github.com/controlplaneio-fluxcd/charts
    - name: Upstream Project
      url: https://github.com/controlplaneio-fluxcd/flux-operator
maintainers:
  - name: ControlPlane Flux Team
    email: flux-enterprise@control-plane.io
keywords:
  - flux
  - fluxcd
  - gitops
  - mcp
  - ai
