name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@f05a280b876a3a1d35a76a91f701e605777853aa # v2.9.1
      - name: Setup Flux Schema CLI
        uses: fluxcd/flux-schema/actions/setup@d802c91e082416f3cc57260d4e97586b8f0731c6 # v0.10.1
      - name: Setup Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      - name: Setup Helm Docs
        uses: gabe565/setup-helm-docs-action@d5c35bdc9133cfbea3b671acadf50a29029e87c2 # v1.0.4
      - run: make plugins manifests lint
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
